/**
 * Database of item prices and Tiers.
 * Maps Item Name -> { price: Number, tier: Number }
 * Based on "Regras de Itens.txt"
 */

export const PRICE_DATA = {
    "Primary Weapons": {
        // Tier 1 (Physical)
        "Dagger": { price: 10, tier: 1 },
        "Broadsword": { price: 20, tier: 1 },
        "Mace": { price: 20, tier: 1 },
        "Cutlass": { price: 20, tier: 1 },
        "Rapier": { price: 20, tier: 1 },
        "Crossbow": { price: 20, tier: 1 },
        "Shortbow": { price: 30, tier: 1 },
        "Longsword": { price: 30, tier: 1 },
        "Battleaxe": { price: 30, tier: 1 },
        "Quarterstaff": { price: 30, tier: 1 },
        "Spear": { price: 30, tier: 1 },
        "Greatsword": { price: 40, tier: 1 },
        "Warhammer": { price: 40, tier: 1 },
        "Halberd": { price: 40, tier: 1 },
        "Longbow": { price: 40, tier: 1 },
        // Tier 1 (Magic)
        "Hand Runes": { price: 30, tier: 1 },
        "Hallowed Axe": { price: 40, tier: 1 },
        "Returning Blade": { price: 40, tier: 1 },
        "Shortstaff": { price: 40, tier: 1 },
        "Wand": { price: 40, tier: 1 },
        "Arcane Gauntlets": { price: 50, tier: 1 },
        "Glowing Rings": { price: 50, tier: 1 },
        "Dualstaff": { price: 50, tier: 1 },
        "Scepter": { price: 50, tier: 1 },
        "Greatstaff": { price: 50, tier: 1 },

        // Tier 2 (Physical)
        "Improved Mace": { price: 110, tier: 2 },
        "Improved Dagger": { price: 120, tier: 2 },
        "Improved Broadsword": { price: 120, tier: 2 },
        "Improved Shortbow": { price: 120, tier: 2 },
        "Improved Crossbow": { price: 120, tier: 2 },
        "Bladed Whip": { price: 120, tier: 2 },
        "Improved Halberd": { price: 120, tier: 2 },
        "Improved Longsword": { price: 130, tier: 2 },
        "Improved Battleaxe": { price: 130, tier: 2 },
        "Improved Cutlass": { price: 130, tier: 2 },
        "Improved Spear": { price: 130, tier: 2 },
        "Improved Warhammer": { price: 130, tier: 2 },
        "Improved Longbow": { price: 130, tier: 2 },
        "Steelforged Halberd": { price: 130, tier: 2 },
        "Improved Quarterstaff": { price: 140, tier: 2 },
        "Improved Rapier": { price: 140, tier: 2 },
        "Gilded Falchion": { price: 140, tier: 2 },
        "Urok Broadsword": { price: 140, tier: 2 },
        "War Scythe": { price: 140, tier: 2 },
        "Blunderbuss": { price: 140, tier: 2 },
        "Greatbow": { price: 140, tier: 2 },
        "Finehair Bow": { price: 140, tier: 2 },
        "Improved Greatsword": { price: 150, tier: 2 },
        "Knuckle Blades": { price: 150, tier: 2 },
        // Tier 2 (Magic)
        "Improved Hallowed Axe": { price: 120, tier: 2 },
        "Improved Hand Runes": { price: 130, tier: 2 },
        "Improved Shortstaff": { price: 130, tier: 2 },
        "Improved Wand": { price: 130, tier: 2 },
        "Improved Dualstaff": { price: 130, tier: 2 },
        "Improved Arcane Gauntlets": { price: 140, tier: 2 },
        "Improved Glowing Rings": { price: 140, tier: 2 },
        "Ego Blade": { price: 140, tier: 2 },
        "Devouring Dagger": { price: 140, tier: 2 },
        "Improved Returning Blade": { price: 150, tier: 2 },
        "Improved Scepter": { price: 150, tier: 2 },
        "Casting Sword": { price: 150, tier: 2 },
        "Yutari Bloodbow": { price: 150, tier: 2 },
        "Elder Bow": { price: 150, tier: 2 },
        "Scepter of Elias": { price: 150, tier: 2 },
        "Wand of Enthrallment": { price: 150, tier: 2 },
        "Keeper's Staff": { price: 150, tier: 2 },
        "Hammer of Exota": { price: 160, tier: 2 },
        "Improved Greatstaff": { price: 170, tier: 2 },

        // Tier 3 (Physical)
        "Advanced Dagger": { price: 500, tier: 3 },
        "Advanced Mace": { price: 550, tier: 3 },
        "Advanced Shortbow": { price: 550, tier: 3 },
        "Advanced Broadsword": { price: 600, tier: 3 },
        "Advanced Cutlass": { price: 600, tier: 3 },
        "Advanced Crossbow": { price: 600, tier: 3 },
        "Advanced Rapier": { price: 650, tier: 3 },
        "Advanced Spear": { price: 650, tier: 3 },
        "Advanced Battleaxe": { price: 700, tier: 3 },
        "Advanced Longsword": { price: 700, tier: 3 },
        "Advanced Quarterstaff": { price: 700, tier: 3 },
        "Advanced Halberd": { price: 750, tier: 3 },
        "Advanced Longbow": { price: 750, tier: 3 },
        "Black Powder Revolver": { price: 800, tier: 3 },
        "Advanced Greatsword": { price: 800, tier: 3 },
        "Labrys Axe": { price: 800, tier: 3 },
        "Advanced Warhammer": { price: 850, tier: 3 },
        "Retractable Saber": { price: 850, tier: 3 },
        "Bravesword": { price: 850, tier: 3 },
        "Spiked Bow": { price: 900, tier: 3 },
        "Talon Blades": { price: 900, tier: 3 },
        "Meridian Cutlass": { price: 900, tier: 3 },
        "Flickerfly Blade": { price: 950, tier: 3 },
        "Double Flail": { price: 950, tier: 3 },
        "Hammer of Wrath": { price: 1000, tier: 3 },
        // Tier 3 (Magic)
        "Advanced Wand": { price: 550, tier: 3 },
        "Advanced Hand Runes": { price: 600, tier: 3 },
        "Advanced Shortstaff": { price: 650, tier: 3 },
        "Advanced Returning Blade": { price: 650, tier: 3 },
        "Advanced Hallowed Axe": { price: 700, tier: 3 },
        "Advanced Dualstaff": { price: 700, tier: 3 },
        "Advanced Scepter": { price: 750, tier: 3 },
        "Advanced Arcane Gauntlets": { price: 800, tier: 3 },
        "Runes of Ruination": { price: 800, tier: 3 },
        "Advanced Glowing Rings": { price: 850, tier: 3 },
        "Mage Orb": { price: 850, tier: 3 },
        "Firestaff": { price: 850, tier: 3 },
        "Advanced Greatstaff": { price: 850, tier: 3 },
        "Ilmari's Rifle": { price: 900, tier: 3 },
        "Gilded Bow": { price: 900, tier: 3 },
        "Ghostblade": { price: 900, tier: 3 },
        "Axe of Fortunis": { price: 950, tier: 3 },
        "Widogast Pendant": { price: 950, tier: 3 },
        "Blessed Anlace": { price: 1000, tier: 3 },

        // Tier 4 (Physical)
        "Legendary Dagger": { price: 1000, tier: 4 },
        "Legendary Mace": { price: 1100, tier: 4 },
        "Legendary Shortbow": { price: 1100, tier: 4 },
        "Legendary Crossbow": { price: 1200, tier: 4 },
        "Legendary Broadsword": { price: 1200, tier: 4 },
        "Legendary Cutlass": { price: 1200, tier: 4 },
        "Curved Dagger": { price: 1300, tier: 4 },
        "Legendary Rapier": { price: 1300, tier: 4 },
        "Legendary Spear": { price: 1300, tier: 4 },
        "Legendary Battleaxe": { price: 1400, tier: 4 },
        "Legendary Longsword": { price: 1400, tier: 4 },
        "Hand Cannon": { price: 1400, tier: 4 },
        "Legendary Quarterstaff": { price: 1500, tier: 4 },
        "Legendary Halberd": { price: 1500, tier: 4 },
        "Legendary Longbow": { price: 1500, tier: 4 },
        "Extended Polearm": { price: 1500, tier: 4 },
        "Dual-Ended Sword": { price: 1600, tier: 4 },
        "Legendary Greatsword": { price: 1600, tier: 4 },
        "Legendary Warhammer": { price: 1600, tier: 4 },
        "Impact Gauntlet": { price: 1700, tier: 4 },
        "Ricochet Axes": { price: 1700, tier: 4 },
        "Swinging Ropeblade": { price: 1800, tier: 4 },
        "Aantari Bow": { price: 1800, tier: 4 },
        "Sledge Axe": { price: 2000, tier: 4 },
        // Tier 4 (Magic)
        "Legendary Hand Runes": { price: 1200, tier: 4 },
        "Legendary Shortstaff": { price: 1200, tier: 4 },
        "Legendary Wand": { price: 1200, tier: 4 },
        "Legendary Hallowed Axe": { price: 1300, tier: 4 },
        "Legendary Returning Blade": { price: 1300, tier: 4 },
        "Legendary Dualstaff": { price: 1400, tier: 4 },
        "Legendary Arcane Gauntlets": { price: 1500, tier: 4 },
        "Legendary Glowing Rings": { price: 1500, tier: 4 },
        "Legendary Scepter": { price: 1500, tier: 4 },
        "Floating Bladeshards": { price: 1500, tier: 4 },
        "Legendary Greatstaff": { price: 1600, tier: 4 },
        "Wand of Essek": { price: 1600, tier: 4 },
        "Magus Revolver": { price: 1600, tier: 4 },
        "Thistlebow": { price: 1700, tier: 4 },
        "Siphoning Gauntlets": { price: 1800, tier: 4 },
        "Midas Scythe": { price: 1800, tier: 4 },
        "Bloodstaff": { price: 1900, tier: 4 },
        "Fusion Gloves": { price: 1900, tier: 4 },
        "Sword of Light & Flame": { price: 2000, tier: 4 }
    },
    "Secondary Weapons": {
        // Tier 1
        "Small Dagger": { price: 10, tier: 1 },
        "Whip": { price: 20, tier: 1 },
        "Shortsword": { price: 20, tier: 1 },
        "Round Shield": { price: 20, tier: 1 },
        "Hand Crossbow": { price: 20, tier: 1 },
        "Grappler": { price: 30, tier: 1 },
        "Tower Shield": { price: 40, tier: 1 },
        // Tier 2
        "Improved Shortsword": { price: 120, tier: 2 },
        "Improved Round Shield": { price: 120, tier: 2 },
        "Improved Hand Crossbow": { price: 120, tier: 2 },
        "Spiked Shield": { price: 120, tier: 2 },
        "Improved Tower Shield": { price: 120, tier: 2 },
        "Improved Small Dagger": { price: 130, tier: 2 },
        "Parrying Dagger": { price: 130, tier: 2 },
        "Improved Whip": { price: 130, tier: 2 },
        "Returning Axe": { price: 130, tier: 2 },
        "Improved Grappler": { price: 140, tier: 2 },
        // Tier 3
        "Advanced Small Dagger": { price: 500, tier: 3 },
        "Advanced Round Shield": { price: 550, tier: 3 },
        "Advanced Whip": { price: 550, tier: 3 },
        "Advanced Shortsword": { price: 600, tier: 3 },
        "Advanced Hand Crossbow": { price: 650, tier: 3 },
        "Advanced Grappler": { price: 650, tier: 3 },
        "Advanced Tower Shield": { price: 700, tier: 3 },
        "Hand Sling": { price: 750, tier: 3 },
        "Buckler": { price: 800, tier: 3 },
        "Powered Gauntlet": { price: 850, tier: 3 },
        // Tier 4
        "Legendary Small Dagger": { price: 1000, tier: 4 },
        "Legendary Round Shield": { price: 1200, tier: 4 },
        "Legendary Whip": { price: 1200, tier: 4 },
        "Legendary Shortsword": { price: 1300, tier: 4 },
        "Legendary Hand Crossbow": { price: 1300, tier: 4 },
        "Knuckle Claws": { price: 1400, tier: 4 },
        "Primer Shard": { price: 1400, tier: 4 },
        "Legendary Grappler": { price: 1500, tier: 4 },
        "Legendary Tower Shield": { price: 1600, tier: 4 },
        "Braveshield": { price: 1700, tier: 4 }
    },
    "Armors": {
        // Tier 1
        "Gambeson Armor": { price: 20, tier: 1 },
        "Leather Armor": { price: 30, tier: 1 },
        "Chainmail Armor": { price: 40, tier: 1 },
        "Full Plate Armor": { price: 50, tier: 1 },
        // Tier 2
        "Improved Gambeson Armor": { price: 120, tier: 2 },
        "Improved Leather Armor": { price: 130, tier: 2 },
        "Tyris Soft Armor": { price: 150, tier: 2 },
        "Improved Chainmail Armor": { price: 160, tier: 2 },
        "Irontree Breastplate Armor": { price: 170, tier: 2 },
        "Runetan Floating Armor": { price: 180, tier: 2 },
        "Harrowbone Armor": { price: 180, tier: 2 },
        "Elundrian Chain Armor": { price: 190, tier: 2 },
        "Rosewild Armor": { price: 200, tier: 2 },
        "Improved Full Plate Armor": { price: 200, tier: 2 },
        // Tier 3
        "Advanced Gambeson Armor": { price: 500, tier: 3 },
        "Spiked Plate Armor": { price: 580, tier: 3 },
        "Advanced Leather Armor": { price: 600, tier: 3 },
        "Bellamoi Fine Armor": { price: 650, tier: 3 },
        "Advanced Chainmail Armor": { price: 700, tier: 3 },
        "Advanced Full Plate Armor": { price: 750, tier: 3 },
        "Dragonscale Armor": { price: 820, tier: 3 },
        "Bladefare Armor": { price: 880, tier: 3 },
        "Monett's Cloak": { price: 880, tier: 3 },
        "Runes of Fortification": { price: 950, tier: 3 },
        // Tier 4
        "Legendary Gambeson Armor": { price: 1000, tier: 4 },
        "Legendary Leather Armor": { price: 1200, tier: 4 },
        "Channeling Armor": { price: 1400, tier: 4 },
        "Veritas Opal Armor": { price: 1500, tier: 4 },
        "Legendary Chainmail Armor": { price: 1500, tier: 4 },
        "Full Fortified Armor": { price: 1600, tier: 4 },
        "Emberwoven Armor": { price: 1700, tier: 4 },
        "Legendary Full Plate Armor": { price: 1800, tier: 4 },
        "Dunamis Silkchain": { price: 1900, tier: 4 },
        "Savior Chainmail": { price: 2000, tier: 4 }
    },
    "Wheelchairs": {
        // Tier 1
        "Light-Frame Wheelchair": { price: 20, tier: 1 },
        "Heavy-Frame Wheelchair": { price: 30, tier: 1 },
        "Arcane-Frame Wheelchair": { price: 40, tier: 1 },
        // Tier 2
        "Improved Light-Frame Wheelchair": { price: 120, tier: 2 },
        "Improved Heavy-Frame Wheelchair": { price: 150, tier: 2 },
        "Improved Arcane-Frame Wheelchair": { price: 180, tier: 2 },
        // Tier 3
        "Advanced Light-Frame Wheelchair": { price: 550, tier: 3 },
        "Advanced Heavy-Frame Wheelchair": { price: 700, tier: 3 },
        "Advanced Arcane-Frame Wheelchair": { price: 850, tier: 3 },
        // Tier 4
        "Legendary Light-Frame Wheelchair": { price: 1200, tier: 4 },
        "Legendary Heavy-Frame Wheelchair": { price: 1500, tier: 4 },
        "Legendary Arcane-Frame Wheelchair": { price: 1800, tier: 4 }
    },
    "Potions": {
        // Tier 1 (Common)
        "Minor Health Potion": { price: 20, tier: 1 },
        "Minor Stamina Potion": { price: 20, tier: 1 },
        "Stride Potion": { price: 10, tier: 1 },
        "Bolster Potion": { price: 10, tier: 1 },
        "Control Potion": { price: 10, tier: 1 },
        "Attune Potion": { price: 10, tier: 1 },
        "Charm Potion": { price: 10, tier: 1 },
        "Enlighten Potion": { price: 10, tier: 1 },
        "Grindletooth Venom": { price: 30, tier: 1 },
        "Potion of Stability": { price: 30, tier: 1 },
        // Tier 2 (Uncommon)
        "Health Potion": { price: 50, tier: 2 },
        "Stamina Potion": { price: 50, tier: 2 },
        "Improved Grindletooth Venom": { price: 60, tier: 2 },
        "Vial of Darksmoke": { price: 60, tier: 2 },
        "Major Stride Potion": { price: 80, tier: 2 },
        "Major Bolster Potion": { price: 80, tier: 2 },
        "Major Control Potion": { price: 80, tier: 2 },
        "Major Attune Potion": { price: 80, tier: 2 },
        "Major Charm Potion": { price: 80, tier: 2 },
        "Major Enlighten Potion": { price: 80, tier: 2 },
        "Blood of the Yorgi": { price: 90, tier: 2 },
        "Homet's Secret Potion": { price: 90, tier: 2 },
        "Redthorn Saliva": { price: 90, tier: 2 },
        // Tier 3 (Rare)
        "Major Health Potion": { price: 200, tier: 3 },
        "Major Stamina Potion": { price: 200, tier: 3 },
        "Ogre Musk": { price: 250, tier: 3 },
        "Wingsprout": { price: 300, tier: 3 },
        "Jar of Lost Voices": { price: 300, tier: 3 },
        "Dragonbloom Tea": { price: 350, tier: 3 },
        "Sleeping Sap": { price: 350, tier: 3 },
        "Feast of Xuria": { price: 400, tier: 3 },
        // Tier 4 (Legendary)
        "Bonding Honey": { price: 500, tier: 4 },
        "Sweet Moss": { price: 500, tier: 4 },
        "Shrinking Potion": { price: 600, tier: 4 },
        "Growing Potion": { price: 600, tier: 4 },
        "Blinding Orb": { price: 700, tier: 4 },
        "Knowledge Stone": { price: 800, tier: 4 },
        "Death Tea": { price: 900, tier: 4 },
        "Stardrop": { price: 1000, tier: 4 }
    },
    "Consumables": {
        // Tier 1
        "Varik Leaves": { price: 20, tier: 1 },
        "Unstable Arcane Shard": { price: 30, tier: 1 },
        // Tier 2
        "Morphing Clay": { price: 60, tier: 2 },
        "Jumping Root": { price: 60, tier: 2 },
        "Snap Powder": { price: 70, tier: 2 },
        "Armor Stitcher": { price: 80, tier: 2 },
        "Gill Salve": { price: 80, tier: 2 },
        "Replication Parchment": { price: 90, tier: 2 },
        "Improved Arcane Shard": { price: 90, tier: 2 },
        // Tier 3
        "Channelstone": { price: 200, tier: 3 },
        "Mythic Dust": { price: 250, tier: 3 },
        "Acidpaste": { price: 250, tier: 3 },
        "Hopehold Flare": { price: 300, tier: 3 },
        "Major Arcane Shard": { price: 300, tier: 3 },
        "Featherbone": { price: 350, tier: 3 },
        "Circle of the Void": { price: 350, tier: 3 },
        "Bridge Seed": { price: 400, tier: 3 },
        // Tier 4
        "Mirror of Marigold": { price: 700, tier: 4 },
        "Stardrop": { price: 1000, tier: 4 }
    },
    "Loot": {
        // Tier 1
        "Premium Bedroll": { price: 20, tier: 1 },
        "Piper Whistle": { price: 20, tier: 1 },
        "Manacles": { price: 20, tier: 1 },
        "Charging Quiver": { price: 30, tier: 1 },
        "Alistair's Torch": { price: 40, tier: 1 },
        "Fire Jar": { price: 40, tier: 1 },
        "Woven Net": { price: 40, tier: 1 },
        "Speaking Orbs": { price: 50, tier: 1 },
        "Arcane Cloak": { price: 50, tier: 1 },
        "Suspended Rod": { price: 50, tier: 1 },
        "Glamour Stone": { price: 50, tier: 1 },
        "Empty Chest": { price: 50, tier: 1 },
        "Companion Case": { price: 50, tier: 1 },
        "Piercing Arrows": { price: 50, tier: 1 },
        "Valorstone": { price: 50, tier: 1 },
        // Tier 2
        "Minor Stamina Potion Recipe": { price: 80, tier: 2 },
        "Minor Health Potion Recipe": { price: 80, tier: 2 },
        "Skeleton Key": { price: 90, tier: 2 },
        "Homing Compasses": { price: 90, tier: 2 },
        "Arcane Prism": { price: 100, tier: 2 },
        "Corrector Sprite": { price: 100, tier: 2 },
        "Gecko Gloves": { price: 100, tier: 2 },
        "Lorekeeper": { price: 120, tier: 2 },
        "Vial of Darksmoke Recipe": { price: 120, tier: 2 },
        "Glider": { price: 150, tier: 2 },
        "Ring of Silence": { price: 150, tier: 2 },
        "Calming Pendant": { price: 150, tier: 2 },
        "Dual Flask": { price: 150, tier: 2 },
        "Bloodstone": { price: 200, tier: 2 },
        "Greatstone": { price: 200, tier: 2 },
        // Tier 3
        "Bag of Ficklesand": { price: 300, tier: 3 },
        "Box of Many Goods": { price: 300, tier: 3 },
        "Ring of Resistance": { price: 400, tier: 3 },
        "Phoenix Feather": { price: 400, tier: 3 },
        "Airblade Charm": { price: 500, tier: 3 },
        "Portal Seed": { price: 600, tier: 3 },
        "Paragon's Chain": { price: 600, tier: 3 },
        "Elusive Amulet": { price: 700, tier: 3 },
        "Hopekeeper Locket": { price: 700, tier: 3 },
        "Infinite Bag": { price: 800, tier: 3 },
        "Stride Relic": { price: 1000, tier: 3 },
        "Bolster Relic": { price: 1000, tier: 3 },
        "Control Relic": { price: 1000, tier: 3 },
        "Attune Relic": { price: 1000, tier: 3 },
        "Charm Relic": { price: 1000, tier: 3 },
        // Tier 4
        "Enlighten Relic": { price: 1000, tier: 4 },
        "Honing Relic": { price: 1000, tier: 4 },
        "Flickerfly Pendant": { price: 1200, tier: 4 },
        "Lakestrider Boots": { price: 1200, tier: 4 },
        "Clay Companion": { price: 1300, tier: 4 },
        "Mythic Dust Recipe": { price: 1400, tier: 4 },
        "Shard of Memory": { price: 1500, tier: 4 },
        "Gem of Alacrity": { price: 1500, tier: 4 },
        "Gem of Might": { price: 1500, tier: 4 },
        "Gem of Precision": { price: 1500, tier: 4 },
        "Gem of Insight": { price: 1500, tier: 4 },
        "Gem of Audacity": { price: 1500, tier: 4 },
        "Gem of Sagacity": { price: 1500, tier: 4 },
        "Ring of Unbreakable Resolve": { price: 2000, tier: 4 },
        "Belt of Unity": { price: 2000, tier: 4 }
    }
};

export const PACK_MAPPING = {
    "Primary Weapons": "daggerheart.weapons",
    "Secondary Weapons": "daggerheart.weapons",
    "Wheelchairs": "daggerheart.weapons",
    "Armors": "daggerheart.armors",
    "Potions": "daggerheart.consumables",
    "Consumables": "daggerheart.consumables",
    "Loot": "daggerheart.loot"
};